pub(crate) mod body;
pub(crate) mod collider;

use crate::math::*;
use body::{Body as InternalBody, BodyKey};
use collider::{Collider, ColliderKey};
use slotmap::SlotMap;
use std::sync::atomic::{AtomicU32, Ordering};

static NEXT_WORLD_ID: AtomicU32 = AtomicU32::new(0);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorldId(u32);

#[derive(Debug)]
pub struct World {
    pub(crate) world_id: WorldId,
    pub(crate) bodies: SlotMap<BodyKey, InternalBody>,
    pub(crate) colliders: SlotMap<ColliderKey, Collider>,
}

// Public API
impl World {
    pub fn body_handles(&self) -> impl Iterator<Item = BodyHandle> {
        self.bodies.keys().map(|body_key| BodyHandle {
            world_id: self.world_id,
            body_key,
        })
    }

    pub fn body(&self, handle: BodyHandle) -> Result<Body<'_>, &'static str> {
        if self.world_id != handle.world_id {
            return Err("Handle was generated by a different world.");
        }
        if !self.bodies.contains_key(handle.body_key) {
            return Err("Handle does not point to a valid body in this world.");
        }
        Ok(Body {
            world: self,
            body_key: handle.body_key,
            cached_body: std::cell::OnceCell::new(),
            cached_collider: std::cell::OnceCell::new(),
        })
    }

    pub fn body_mut(&mut self, handle: BodyHandle) -> Result<BodyMut<'_>, &'static str> {
        if self.world_id != handle.world_id {
            return Err("Handle was generated by a different world.");
        }
        if !self.bodies.contains_key(handle.body_key) {
            return Err("Handle does not point to a valid body in this world.");
        }
        Ok(BodyMut {
            world: self,
            body_key: handle.body_key,
        })
    }

    pub fn add_body(
        &mut self,
        position: Vec2,
        velocity: Vec2,
        mass: f32,
        shape: Shape,
    ) -> Result<BodyHandle, &'static str> {
        if mass < 0.000_000_001 {
            return Err("Mass is too small.");
        }
        let collider = Collider {
            body_key: Default::default(),
            shape,
        };
        let collider_key = self.colliders.insert(collider);
        let body = InternalBody {
            position,
            velocity,
            accumulated_impulse: Vec2::ZERO,
            mass_inv: 1.0 / mass,
            collider_key,
        };
        let body_key = self.bodies.insert(body);
        self.colliders.get_mut(collider_key).unwrap().body_key = body_key; // Safety: We've just inserted the collider to the slotmap.
        Ok(BodyHandle {
            world_id: self.world_id,
            body_key,
        })
    }

    /// Find a body that contains a world space position.
    ///
    /// When bodies are overlapping, it is possible to have more than one body at the query point.
    /// This function will return the body that comes first in its internal slotmap, which makes it deterministic.
    pub fn query_point(&self, position: Vec2) -> Option<BodyHandle> {
        // TODO: Use quadtree or BVH to find bodies.
        for collider in self.colliders.values() {
            let body = self.bodies.get(collider.body_key).unwrap(); // Safety: Colliders in `world.colliders` will always have valid body keys.
            let body_pos = body.position;
            match collider.shape {
                Shape::Circle(circle) => {
                    if (position - body_pos).length_squared() <= circle.radius.powi(2) {
                        return Some(BodyHandle {
                            world_id: self.world_id,
                            body_key: collider.body_key,
                        });
                    }
                }
            }
        }
        None
    }
}

impl Default for World {
    fn default() -> Self {
        let world_id = WorldId(NEXT_WORLD_ID.fetch_add(1, Ordering::Relaxed));
        Self {
            world_id,
            bodies: SlotMap::with_key(),
            colliders: SlotMap::with_key(),
        }
    }
}

impl PartialEq for World {
    fn eq(&self, other: &Self) -> bool {
        self.world_id == other.world_id
    }
}

impl Eq for World {}

/// A persistent handle to a specific body in the world.
///
/// Giving users a shared/mutable reference to the internal `InternalBody` instances would cause borrow checker hell.
/// Instead we return `BodyHandle`s in every body-related API as a "handle" to the actual body.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BodyHandle {
    pub(crate) world_id: WorldId,
    pub(crate) body_key: BodyKey,
}

/// An immutable view to a body (and its collider). Can only be returned by using a handle on a world.
#[derive(Debug)]
pub struct Body<'a> {
    world: &'a World,
    body_key: BodyKey,
    // We cache references to bodies and colliders to avoid repeated access to the container.
    cached_body: std::cell::OnceCell<&'a InternalBody>,
    cached_collider: std::cell::OnceCell<&'a Collider>,
}

impl Body<'_> {
    fn body(&self) -> &InternalBody {
        self.cached_body
            .get_or_init(|| self.world.bodies.get(self.body_key).unwrap())
    }

    fn collider(&self) -> &Collider {
        self.cached_collider
            .get_or_init(|| self.world.colliders.get(self.body().collider_key).unwrap())
    }

    pub fn handle(&self) -> BodyHandle {
        BodyHandle {
            world_id: self.world.world_id,
            body_key: self.body_key,
        }
    }
    pub fn position(&self) -> Vec2 {
        self.body().position
    }

    pub fn velocity(&self) -> Vec2 {
        self.body().velocity
    }

    pub fn accumulated_impulse(&self) -> Vec2 {
        self.body().accumulated_impulse
    }

    pub fn mass_inv(&self) -> f32 {
        self.body().mass_inv
    }

    pub fn shape(&self) -> Shape {
        self.collider().shape
    }
}

impl<'a> PartialEq for Body<'a> {
    fn eq(&self, other: &Self) -> bool {
        self.world == other.world && self.body_key == other.body_key
    }
}

impl<'a> Eq for Body<'a> {}

impl<'a> Clone for Body<'a> {
    fn clone(&self) -> Self {
        Body {
            world: self.world,
            body_key: self.body_key,
            cached_body: self.cached_body.clone(), // Cloning `OnceCell<&InternalBody>`s are cheap because `&InternalBody`s are `Copy`.
            cached_collider: self.cached_collider.clone(), // Same here. We clone these to give cloned `Body`s a warm cache.
        }
    }
}

/// A mutable view to a body (and its collider). Can only be returned by using a handle on a world.
#[derive(Debug)]
pub struct BodyMut<'a> {
    world: &'a mut World,
    body_key: BodyKey,
    // We can't cache references here, because since we have a mutable reference to the world, we might use it to invalidate bodies and colliders.
}

impl BodyMut<'_> {
    fn body(&self) -> &InternalBody {
        self.world.bodies.get(self.body_key).unwrap() // Safety: A valid `body_mut` ensures that `body_mut.world.contains_key(body_mut.body_key)`.
    }

    fn body_mut(&mut self) -> &mut InternalBody {
        self.world.bodies.get_mut(self.body_key).unwrap() // Safety: A valid `body_mut` ensures that `body_mut.world.contains_key(body_mut.body_key)`.
    }

    fn collider(&self) -> &Collider {
        self.world.colliders.get(self.body().collider_key).unwrap()
    }

    fn collider_mut(&mut self) -> &mut Collider {
        self.world
            .colliders
            .get_mut(self.body().collider_key)
            .unwrap()
    }

    pub fn handle(&self) -> BodyHandle {
        BodyHandle {
            world_id: self.world.world_id,
            body_key: self.body_key,
        }
    }
    pub fn position(&self) -> Vec2 {
        self.body().position
    }

    pub fn velocity(&self) -> Vec2 {
        self.body().velocity
    }

    pub fn accumulated_impulse(&self) -> Vec2 {
        self.body().accumulated_impulse
    }

    pub fn mass_inv(&self) -> f32 {
        self.body().mass_inv
    }

    pub fn shape(&self) -> Shape {
        self.collider().shape
    }

    // Mutable accessors
    pub fn position_mut(&mut self) -> &mut Vec2 {
        &mut self.body_mut().position
    }

    pub fn velocity_mut(&mut self) -> &mut Vec2 {
        &mut self.body_mut().velocity
    }

    pub fn accumulated_impulse_mut(&mut self) -> &mut Vec2 {
        &mut self.body_mut().accumulated_impulse
    }

    pub fn mass_inv_mut(&mut self) -> &mut f32 {
        &mut self.body_mut().mass_inv
    }

    pub fn shape_mut(&mut self) -> &mut Shape {
        &mut self.collider_mut().shape
    }
}
