pub(crate) mod body;
pub(crate) mod collider;

use crate::math::*;
use body::{Body, BodyKey};
use collider::{Collider, ColliderKey};
use slotmap::SlotMap;
use std::sync::atomic::{AtomicU32, Ordering};

static NEXT_WORLD_ID: AtomicU32 = AtomicU32::new(0);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorldId(u32);

#[derive(Debug)]
pub struct World {
    pub(crate) world_id: WorldId,
    pub(crate) bodies: SlotMap<BodyKey, Body>,
    pub(crate) colliders: SlotMap<ColliderKey, Collider>,
}

// Public API
impl World {
    pub fn body_handles(&self) -> impl Iterator<Item = BodyHandle> {
        self.bodies.keys().map(|body_key| BodyHandle {
            world_id: self.world_id,
            body_key,
        })
    }

    pub fn bodies(&self) -> impl Iterator<Item = BodyView<'_>> {
        self.bodies.keys().map(|body_key| BodyView {
            world: self,
            body_key,
        })
    }

    pub fn body(&self, handle: BodyHandle) -> Result<BodyView<'_>, &'static str> {
        if self.world_id != handle.world_id {
            return Err("Handle was generated by a different world.");
        }
        if !self.bodies.contains_key(handle.body_key) {
            return Err("Handle does not point to a valid body in this world.");
        }
        Ok(BodyView {
            world: self,
            body_key: handle.body_key,
        })
    }

    pub fn add_body(
        &mut self,
        position: Vec2,
        velocity: Vec2,
        mass: f32,
        shape: Shape,
    ) -> Result<BodyHandle, &'static str> {
        if mass < 0.000_000_001 {
            return Err("Mass is too small.");
        }
        let collider = Collider {
            body_key: Default::default(),
            shape,
        };
        let collider_key = self.colliders.insert(collider);
        let body = Body {
            position,
            velocity,
            accumulated_impulse: Vec2::ZERO,
            inverse_mass: 1.0 / mass,
            collider_key,
        };
        let body_key = self.bodies.insert(body);
        self.colliders.get_mut(collider_key).unwrap().body_key = body_key; // Safety: We've just inserted the collider to the slotmap.
        Ok(BodyHandle {
            world_id: self.world_id,
            body_key,
        })
    }
}

impl Default for World {
    fn default() -> Self {
        let world_id = WorldId(NEXT_WORLD_ID.fetch_add(1, Ordering::Relaxed));
        Self {
            world_id,
            bodies: SlotMap::with_key(),
            colliders: SlotMap::with_key(),
        }
    }
}

/// A persistent handle to a specific body in the world.
///
/// Giving users a shared/mutable reference to the internal `Body` instances would cause borrow checker hell.
/// Instead we return `BodyHandle`s in every body-related API as a "handle" to the actual body.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BodyHandle {
    pub(crate) world_id: WorldId,
    pub(crate) body_key: BodyKey,
}

/// An immutable view to a specific body in the world.
///
/// `BodyHandle`s can only be used in the world they were produced from.
/// But storing a reference to their world will prevent any other mutable access to the world.
/// Instead, the user does `let body_view = world.body(body_handle);`, and use the `body_view` object to interact with bodies.
#[derive(Debug, Clone, Copy)]
pub struct BodyView<'a> {
    pub(crate) world: &'a World,
    pub(crate) body_key: BodyKey,
    // TODO: Cache the result of `body()` and reuse it for following `position()` / `velocity()` call.
}

impl BodyView<'_> {
    /// Helper function to fetch and cache (TODO) a `&Body` from the world.
    fn body(&self) -> &Body {
        self.world.bodies.get(self.body_key).unwrap() // Safety: This can't fail, as `world.body(handle)`, the only way to get a bodyview, validates the key.
    }

    pub fn position(&self) -> Vec2 {
        self.body().position
    }

    pub fn velocity(&self) -> Vec2 {
        self.body().velocity
    }

    pub fn accumulated_impulse(&self) -> Vec2 {
        self.body().accumulated_impulse
    }

    pub fn mass(&self) -> f32 {
        1.0 / self.body().inverse_mass
    }

    pub fn shape(&self) -> Shape {
        let collider_key = self.body().collider_key;
        self.world.colliders.get(collider_key).unwrap().shape // Safety: This can't fail, as colliders are bound to bodies and only removed from the slotmap when they are detached.
    }

    // TODO: Modifiers for bodies.
}
