pub(crate) mod body;
pub(crate) mod collider;

use crate::math::*;
use body::{Body as InternalBody, BodyKey};
use collider::{Collider, ColliderKey};
use slotmap::SlotMap;
use std::sync::atomic::{AtomicU32, Ordering};

static NEXT_WORLD_ID: AtomicU32 = AtomicU32::new(0);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorldId(u32);

#[derive(Debug)]
pub struct World {
    pub(crate) world_id: WorldId,
    pub(crate) bodies: SlotMap<BodyKey, InternalBody>,
    pub(crate) colliders: SlotMap<ColliderKey, Collider>,
}

// Public API
impl World {
    pub fn body_handles(&self) -> impl Iterator<Item = BodyHandle> {
        self.bodies.keys().map(|body_key| BodyHandle {
            world_id: self.world_id,
            body_key,
        })
    }

    pub fn body(&self, handle: BodyHandle) -> Result<Body<'_>, &'static str> {
        if self.world_id != handle.world_id {
            return Err("Handle was generated by a different world.");
        }
        if !self.bodies.contains_key(handle.body_key) {
            return Err("Handle does not point to a valid body in this world.");
        }
        let body = self.bodies.get(handle.body_key).unwrap();
        let collider = self.colliders.get(body.collider_key).unwrap();
        Ok(Body {
            handle,
            body,
            collider,
        })
    }

    pub fn body_mut(&mut self, handle: BodyHandle) -> Result<BodyMut<'_>, &'static str> {
        if self.world_id != handle.world_id {
            return Err("Handle was generated by a different world.");
        }
        if !self.bodies.contains_key(handle.body_key) {
            return Err("Handle does not point to a valid body in this world.");
        }
        let body = self.bodies.get_mut(handle.body_key).unwrap();
        let collider = self.colliders.get_mut(body.collider_key).unwrap();
        Ok(BodyMut {
            handle,
            body,
            collider,
        })
    }

    pub fn disjoint_body_mut<const N: usize>(
        &mut self,
        handles: [BodyHandle; N],
    ) -> Result<[BodyMut<'_>; N], &'static str> {
        for handle in handles {
            if self.world_id != handle.world_id {
                return Err("Handle was generated by a different world.");
            }
            if !self.bodies.contains_key(handle.body_key) {
                return Err("Handle does not point to a valid body in this world.");
            }
        }
        let body_keys = handles.map(|handle| handle.body_key);
        let bodies = self
            .bodies
            .get_disjoint_mut(body_keys)
            .ok_or("Handles weren't disjoint.")?;
        let collider_keys: [ColliderKey; N] = std::array::from_fn(|i| bodies[i].collider_key);
        let colliders = self.colliders.get_disjoint_mut(collider_keys).unwrap(); // Safety: Bodies were shown to be disjoint. And different bodies don't share same colliders.

        let mut bodies = bodies.map(Some);
        let mut colliders = colliders.map(Some);

        Ok(std::array::from_fn(|i| {
            let handle = handles[i]; // `BodyHandle`s are `Copy`, so we can copy them out from `&handles`.
            // But `&mut T`s are not `Copy` (and shouldn't be), so we can't just copy them from `&bodies`.
            // Instead, we "move" values out and leave the old array as `None` using `Option::take()`.
            let body = bodies[i].take().unwrap();
            let collider = colliders[i].take().unwrap();

            BodyMut {
                handle,
                body,
                collider,
            }
        }))
    }

    pub fn add_body(
        &mut self,
        position: Vec2,
        velocity: Vec2,
        mass: f32,
        shape: Shape,
    ) -> Result<BodyHandle, &'static str> {
        if mass < 0.000_000_001 {
            return Err("Mass is too small.");
        }
        let collider = Collider {
            body_key: Default::default(),
            shape,
        };
        let collider_key = self.colliders.insert(collider);
        let body = InternalBody {
            position,
            velocity,
            accumulated_impulse: Vec2::ZERO,
            mass_inv: 1.0 / mass,
            collider_key,
        };
        let body_key = self.bodies.insert(body);
        self.colliders.get_mut(collider_key).unwrap().body_key = body_key; // Safety: We've just inserted the collider to the slotmap.
        Ok(BodyHandle {
            world_id: self.world_id,
            body_key,
        })
    }

    /// Find a body that contains a world space position.
    ///
    /// When bodies are overlapping, it is possible to have more than one body at the query point.
    /// This function will return the body that comes first in its internal slotmap, which makes it deterministic.
    pub fn query_point(&self, position: Vec2) -> Option<BodyHandle> {
        // TODO: Use quadtree or BVH to find bodies.
        for collider in self.colliders.values() {
            let body = self.bodies.get(collider.body_key).unwrap(); // Safety: Colliders in `world.colliders` will always have valid body keys.
            let body_pos = body.position;
            match collider.shape {
                Shape::Circle(circle) => {
                    if (position - body_pos).length_squared() <= circle.radius.powi(2) {
                        return Some(BodyHandle {
                            world_id: self.world_id,
                            body_key: collider.body_key,
                        });
                    }
                }
            }
        }
        None
    }
}

impl Default for World {
    fn default() -> Self {
        let world_id = WorldId(NEXT_WORLD_ID.fetch_add(1, Ordering::Relaxed));
        Self {
            world_id,
            bodies: SlotMap::with_key(),
            colliders: SlotMap::with_key(),
        }
    }
}

/// A persistent handle to a specific body in the world.
///
/// Giving users a shared/mutable reference to the internal `InternalBody` instances would cause borrow checker hell.
/// Instead we return `BodyHandle`s in every body-related API as a "handle" to the actual body.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BodyHandle {
    pub(crate) world_id: WorldId,
    pub(crate) body_key: BodyKey,
}

/// A thin wrapper around a shared reference to a body (and its collider) in world. Can only be returned by using a handle on a world.
#[derive(Debug, Clone, Copy)]
pub struct Body<'a> {
    handle: BodyHandle,
    body: &'a InternalBody,
    collider: &'a Collider,
}

impl Body<'_> {
    pub fn handle(&self) -> BodyHandle {
        self.handle
    }
    pub fn position(&self) -> Vec2 {
        self.body.position
    }

    pub fn velocity(&self) -> Vec2 {
        self.body.velocity
    }

    pub fn accumulated_impulse(&self) -> Vec2 {
        self.body.accumulated_impulse
    }

    pub fn mass_inv(&self) -> f32 {
        self.body.mass_inv
    }

    pub fn shape(&self) -> Shape {
        self.collider.shape
    }
}

impl<'a> PartialEq for Body<'a> {
    fn eq(&self, other: &Self) -> bool {
        self.handle == other.handle
    }
}

impl<'a> Eq for Body<'a> {}

/// A thin wrapper around a mutale reference to a body (and its collider) in world. Can only be returned by using a handle on a world.
#[derive(Debug)]
pub struct BodyMut<'a> {
    handle: BodyHandle,
    body: &'a mut InternalBody,
    collider: &'a mut Collider,
}

impl BodyMut<'_> {
    pub fn handle(&self) -> BodyHandle {
        self.handle
    }

    pub fn position(&self) -> Vec2 {
        self.body.position
    }

    pub fn velocity(&self) -> Vec2 {
        self.body.velocity
    }

    pub fn accumulated_impulse(&self) -> Vec2 {
        self.body.accumulated_impulse
    }

    pub fn mass_inv(&self) -> f32 {
        self.body.mass_inv
    }

    pub fn shape(&self) -> Shape {
        self.collider.shape
    }

    // Mutable accessors
    pub fn position_mut(&mut self) -> &mut Vec2 {
        &mut self.body.position
    }

    pub fn velocity_mut(&mut self) -> &mut Vec2 {
        &mut self.body.velocity
    }

    pub fn accumulated_impulse_mut(&mut self) -> &mut Vec2 {
        &mut self.body.accumulated_impulse
    }

    pub fn mass_inv_mut(&mut self) -> &mut f32 {
        &mut self.body.mass_inv
    }

    pub fn shape_mut(&mut self) -> &mut Shape {
        &mut self.collider.shape
    }
}
